markdown: rdiscount
pygments: true
permalink: /:year/:title
rdiscount:
  extensions: [smart]
title : Adrien Brault
production_url : http://adrienbrault.net
description: "Hey!"
disqus_shortname: adrienbrault
analytics: UA-42337429-1
author :
  name : AdrienBrault
  github : AdrienBrault
  twitter : AdrienBrault
  email: adrien.brault@gmail.com
exclude: [node_modules, bower_components]
